// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArticleProtoc.proto

package protoc;

public final class ArticleProtoc {
  private ArticleProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ArticleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 article_id = 1;
    /**
     * <code>required int32 article_id = 1;</code>
     */
    boolean hasArticleId();
    /**
     * <code>required int32 article_id = 1;</code>
     */
    int getArticleId();

    // required bytes uv = 2;
    /**
     * <code>required bytes uv = 2;</code>
     */
    boolean hasUv();
    /**
     * <code>required bytes uv = 2;</code>
     */
    com.google.protobuf.ByteString getUv();

    // optional string article_excerpt = 3;
    /**
     * <code>optional string article_excerpt = 3;</code>
     */
    boolean hasArticleExcerpt();
    /**
     * <code>optional string article_excerpt = 3;</code>
     */
    java.lang.String getArticleExcerpt();
    /**
     * <code>optional string article_excerpt = 3;</code>
     */
    com.google.protobuf.ByteString
        getArticleExcerptBytes();

    // repeated string article_picture = 4;
    /**
     * <code>repeated string article_picture = 4;</code>
     */
    java.util.List<java.lang.String>
    getArticlePictureList();
    /**
     * <code>repeated string article_picture = 4;</code>
     */
    int getArticlePictureCount();
    /**
     * <code>repeated string article_picture = 4;</code>
     */
    java.lang.String getArticlePicture(int index);
    /**
     * <code>repeated string article_picture = 4;</code>
     */
    com.google.protobuf.ByteString
        getArticlePictureBytes(int index);
  }
  /**
   * Protobuf type {@code protoc.Article}
   */
  public static final class Article extends
      com.google.protobuf.GeneratedMessage
      implements ArticleOrBuilder {
    // Use Article.newBuilder() to construct.
    private Article(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Article(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Article defaultInstance;
    public static Article getDefaultInstance() {
      return defaultInstance;
    }

    public Article getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Article(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              articleId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              uv_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              articleExcerpt_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                articlePicture_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              articlePicture_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          articlePicture_ = new com.google.protobuf.UnmodifiableLazyStringList(articlePicture_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoc.ArticleProtoc.internal_static_protoc_Article_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoc.ArticleProtoc.internal_static_protoc_Article_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoc.ArticleProtoc.Article.class, protoc.ArticleProtoc.Article.Builder.class);
    }

    public static com.google.protobuf.Parser<Article> PARSER =
        new com.google.protobuf.AbstractParser<Article>() {
      public Article parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Article(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Article> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 article_id = 1;
    public static final int ARTICLE_ID_FIELD_NUMBER = 1;
    private int articleId_;
    /**
     * <code>required int32 article_id = 1;</code>
     */
    public boolean hasArticleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 article_id = 1;</code>
     */
    public int getArticleId() {
      return articleId_;
    }

    // required bytes uv = 2;
    public static final int UV_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString uv_;
    /**
     * <code>required bytes uv = 2;</code>
     */
    public boolean hasUv() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes uv = 2;</code>
     */
    public com.google.protobuf.ByteString getUv() {
      return uv_;
    }

    // optional string article_excerpt = 3;
    public static final int ARTICLE_EXCERPT_FIELD_NUMBER = 3;
    private java.lang.Object articleExcerpt_;
    /**
     * <code>optional string article_excerpt = 3;</code>
     */
    public boolean hasArticleExcerpt() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string article_excerpt = 3;</code>
     */
    public java.lang.String getArticleExcerpt() {
      java.lang.Object ref = articleExcerpt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          articleExcerpt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string article_excerpt = 3;</code>
     */
    public com.google.protobuf.ByteString
        getArticleExcerptBytes() {
      java.lang.Object ref = articleExcerpt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        articleExcerpt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string article_picture = 4;
    public static final int ARTICLE_PICTURE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList articlePicture_;
    /**
     * <code>repeated string article_picture = 4;</code>
     */
    public java.util.List<java.lang.String>
        getArticlePictureList() {
      return articlePicture_;
    }
    /**
     * <code>repeated string article_picture = 4;</code>
     */
    public int getArticlePictureCount() {
      return articlePicture_.size();
    }
    /**
     * <code>repeated string article_picture = 4;</code>
     */
    public java.lang.String getArticlePicture(int index) {
      return articlePicture_.get(index);
    }
    /**
     * <code>repeated string article_picture = 4;</code>
     */
    public com.google.protobuf.ByteString
        getArticlePictureBytes(int index) {
      return articlePicture_.getByteString(index);
    }

    private void initFields() {
      articleId_ = 0;
      uv_ = com.google.protobuf.ByteString.EMPTY;
      articleExcerpt_ = "";
      articlePicture_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasArticleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, articleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, uv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getArticleExcerptBytes());
      }
      for (int i = 0; i < articlePicture_.size(); i++) {
        output.writeBytes(4, articlePicture_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, articleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, uv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getArticleExcerptBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < articlePicture_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(articlePicture_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getArticlePictureList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protoc.ArticleProtoc.Article parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoc.ArticleProtoc.Article parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoc.ArticleProtoc.Article parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoc.ArticleProtoc.Article parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoc.ArticleProtoc.Article parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protoc.ArticleProtoc.Article parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protoc.ArticleProtoc.Article parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protoc.ArticleProtoc.Article parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protoc.ArticleProtoc.Article parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protoc.ArticleProtoc.Article parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protoc.ArticleProtoc.Article prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoc.Article}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protoc.ArticleProtoc.ArticleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoc.ArticleProtoc.internal_static_protoc_Article_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoc.ArticleProtoc.internal_static_protoc_Article_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoc.ArticleProtoc.Article.class, protoc.ArticleProtoc.Article.Builder.class);
      }

      // Construct using protoc.ArticleProtoc.Article.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        articleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        uv_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        articleExcerpt_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        articlePicture_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoc.ArticleProtoc.internal_static_protoc_Article_descriptor;
      }

      public protoc.ArticleProtoc.Article getDefaultInstanceForType() {
        return protoc.ArticleProtoc.Article.getDefaultInstance();
      }

      public protoc.ArticleProtoc.Article build() {
        protoc.ArticleProtoc.Article result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protoc.ArticleProtoc.Article buildPartial() {
        protoc.ArticleProtoc.Article result = new protoc.ArticleProtoc.Article(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.articleId_ = articleId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uv_ = uv_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.articleExcerpt_ = articleExcerpt_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          articlePicture_ = new com.google.protobuf.UnmodifiableLazyStringList(
              articlePicture_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.articlePicture_ = articlePicture_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoc.ArticleProtoc.Article) {
          return mergeFrom((protoc.ArticleProtoc.Article)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoc.ArticleProtoc.Article other) {
        if (other == protoc.ArticleProtoc.Article.getDefaultInstance()) return this;
        if (other.hasArticleId()) {
          setArticleId(other.getArticleId());
        }
        if (other.hasUv()) {
          setUv(other.getUv());
        }
        if (other.hasArticleExcerpt()) {
          bitField0_ |= 0x00000004;
          articleExcerpt_ = other.articleExcerpt_;
          onChanged();
        }
        if (!other.articlePicture_.isEmpty()) {
          if (articlePicture_.isEmpty()) {
            articlePicture_ = other.articlePicture_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureArticlePictureIsMutable();
            articlePicture_.addAll(other.articlePicture_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasArticleId()) {
          
          return false;
        }
        if (!hasUv()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoc.ArticleProtoc.Article parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoc.ArticleProtoc.Article) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 article_id = 1;
      private int articleId_ ;
      /**
       * <code>required int32 article_id = 1;</code>
       */
      public boolean hasArticleId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 article_id = 1;</code>
       */
      public int getArticleId() {
        return articleId_;
      }
      /**
       * <code>required int32 article_id = 1;</code>
       */
      public Builder setArticleId(int value) {
        bitField0_ |= 0x00000001;
        articleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 article_id = 1;</code>
       */
      public Builder clearArticleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        articleId_ = 0;
        onChanged();
        return this;
      }

      // required bytes uv = 2;
      private com.google.protobuf.ByteString uv_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes uv = 2;</code>
       */
      public boolean hasUv() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes uv = 2;</code>
       */
      public com.google.protobuf.ByteString getUv() {
        return uv_;
      }
      /**
       * <code>required bytes uv = 2;</code>
       */
      public Builder setUv(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes uv = 2;</code>
       */
      public Builder clearUv() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uv_ = getDefaultInstance().getUv();
        onChanged();
        return this;
      }

      // optional string article_excerpt = 3;
      private java.lang.Object articleExcerpt_ = "";
      /**
       * <code>optional string article_excerpt = 3;</code>
       */
      public boolean hasArticleExcerpt() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string article_excerpt = 3;</code>
       */
      public java.lang.String getArticleExcerpt() {
        java.lang.Object ref = articleExcerpt_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          articleExcerpt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string article_excerpt = 3;</code>
       */
      public com.google.protobuf.ByteString
          getArticleExcerptBytes() {
        java.lang.Object ref = articleExcerpt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          articleExcerpt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string article_excerpt = 3;</code>
       */
      public Builder setArticleExcerpt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        articleExcerpt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string article_excerpt = 3;</code>
       */
      public Builder clearArticleExcerpt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        articleExcerpt_ = getDefaultInstance().getArticleExcerpt();
        onChanged();
        return this;
      }
      /**
       * <code>optional string article_excerpt = 3;</code>
       */
      public Builder setArticleExcerptBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        articleExcerpt_ = value;
        onChanged();
        return this;
      }

      // repeated string article_picture = 4;
      private com.google.protobuf.LazyStringList articlePicture_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArticlePictureIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          articlePicture_ = new com.google.protobuf.LazyStringArrayList(articlePicture_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string article_picture = 4;</code>
       */
      public java.util.List<java.lang.String>
          getArticlePictureList() {
        return java.util.Collections.unmodifiableList(articlePicture_);
      }
      /**
       * <code>repeated string article_picture = 4;</code>
       */
      public int getArticlePictureCount() {
        return articlePicture_.size();
      }
      /**
       * <code>repeated string article_picture = 4;</code>
       */
      public java.lang.String getArticlePicture(int index) {
        return articlePicture_.get(index);
      }
      /**
       * <code>repeated string article_picture = 4;</code>
       */
      public com.google.protobuf.ByteString
          getArticlePictureBytes(int index) {
        return articlePicture_.getByteString(index);
      }
      /**
       * <code>repeated string article_picture = 4;</code>
       */
      public Builder setArticlePicture(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArticlePictureIsMutable();
        articlePicture_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string article_picture = 4;</code>
       */
      public Builder addArticlePicture(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArticlePictureIsMutable();
        articlePicture_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string article_picture = 4;</code>
       */
      public Builder addAllArticlePicture(
          java.lang.Iterable<java.lang.String> values) {
        ensureArticlePictureIsMutable();
        super.addAll(values, articlePicture_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string article_picture = 4;</code>
       */
      public Builder clearArticlePicture() {
        articlePicture_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string article_picture = 4;</code>
       */
      public Builder addArticlePictureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArticlePictureIsMutable();
        articlePicture_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoc.Article)
    }

    static {
      defaultInstance = new Article(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoc.Article)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoc_Article_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoc_Article_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ArticleProtoc.proto\022\006protoc\"[\n\007Article" +
      "\022\022\n\narticle_id\030\001 \002(\005\022\n\n\002uv\030\002 \002(\014\022\027\n\017arti" +
      "cle_excerpt\030\003 \001(\t\022\027\n\017article_picture\030\004 \003" +
      "(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protoc_Article_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protoc_Article_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoc_Article_descriptor,
              new java.lang.String[] { "ArticleId", "Uv", "ArticleExcerpt", "ArticlePicture", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
