package entity;
 /* Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-02-22")
public class AnswerResults implements org.apache.thrift.TBase<AnswerResults, AnswerResults._Fields>, java.io.Serializable, Cloneable, Comparable<AnswerResults> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AnswerResults");

  private static final org.apache.thrift.protocol.TField ANSWER_RESULTS_FIELD_DESC = new org.apache.thrift.protocol.TField("answerResults", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AnswerResultsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AnswerResultsTupleSchemeFactory());
  }

  public List<AnswerResult> answerResults; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ANSWER_RESULTS((short)1, "answerResults");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ANSWER_RESULTS
          return ANSWER_RESULTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.ANSWER_RESULTS};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ANSWER_RESULTS, new org.apache.thrift.meta_data.FieldMetaData("answerResults", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AnswerResult.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AnswerResults.class, metaDataMap);
  }

  public AnswerResults() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AnswerResults(AnswerResults other) {
    if (other.isSetAnswerResults()) {
      List<AnswerResult> __this__answerResults = new ArrayList<AnswerResult>(other.answerResults.size());
      for (AnswerResult other_element : other.answerResults) {
        __this__answerResults.add(new AnswerResult(other_element));
      }
      this.answerResults = __this__answerResults;
    }
  }

  public AnswerResults deepCopy() {
    return new AnswerResults(this);
  }

  @Override
  public void clear() {
    this.answerResults = null;
  }

  public int getAnswerResultsSize() {
    return (this.answerResults == null) ? 0 : this.answerResults.size();
  }

  public java.util.Iterator<AnswerResult> getAnswerResultsIterator() {
    return (this.answerResults == null) ? null : this.answerResults.iterator();
  }

  public void addToAnswerResults(AnswerResult elem) {
    if (this.answerResults == null) {
      this.answerResults = new ArrayList<AnswerResult>();
    }
    this.answerResults.add(elem);
  }

  public List<AnswerResult> getAnswerResults() {
    return this.answerResults;
  }

  public AnswerResults setAnswerResults(List<AnswerResult> answerResults) {
    this.answerResults = answerResults;
    return this;
  }

  public void unsetAnswerResults() {
    this.answerResults = null;
  }

  /** Returns true if field answerResults is set (has been assigned a value) and false otherwise */
  public boolean isSetAnswerResults() {
    return this.answerResults != null;
  }

  public void setAnswerResultsIsSet(boolean value) {
    if (!value) {
      this.answerResults = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ANSWER_RESULTS:
      if (value == null) {
        unsetAnswerResults();
      } else {
        setAnswerResults((List<AnswerResult>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ANSWER_RESULTS:
      return getAnswerResults();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ANSWER_RESULTS:
      return isSetAnswerResults();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AnswerResults)
      return this.equals((AnswerResults)that);
    return false;
  }

  public boolean equals(AnswerResults that) {
    if (that == null)
      return false;

    boolean this_present_answerResults = true && this.isSetAnswerResults();
    boolean that_present_answerResults = true && that.isSetAnswerResults();
    if (this_present_answerResults || that_present_answerResults) {
      if (!(this_present_answerResults && that_present_answerResults))
        return false;
      if (!this.answerResults.equals(that.answerResults))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_answerResults = true && (isSetAnswerResults());
    list.add(present_answerResults);
    if (present_answerResults)
      list.add(answerResults);

    return list.hashCode();
  }

  @Override
  public int compareTo(AnswerResults other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetAnswerResults()).compareTo(other.isSetAnswerResults());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAnswerResults()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.answerResults, other.answerResults);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AnswerResults(");
    boolean first = true;

    if (isSetAnswerResults()) {
      sb.append("answerResults:");
      if (this.answerResults == null) {
        sb.append("null");
      } else {
        sb.append(this.answerResults);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AnswerResultsStandardSchemeFactory implements SchemeFactory {
    public AnswerResultsStandardScheme getScheme() {
      return new AnswerResultsStandardScheme();
    }
  }

  private static class AnswerResultsStandardScheme extends StandardScheme<AnswerResults> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AnswerResults struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ANSWER_RESULTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.answerResults = new ArrayList<AnswerResult>(_list8.size);
                AnswerResult _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new AnswerResult();
                  _elem9.read(iprot);
                  struct.answerResults.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setAnswerResultsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AnswerResults struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.answerResults != null) {
        if (struct.isSetAnswerResults()) {
          oprot.writeFieldBegin(ANSWER_RESULTS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.answerResults.size()));
            for (AnswerResult _iter11 : struct.answerResults)
            {
              _iter11.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AnswerResultsTupleSchemeFactory implements SchemeFactory {
    public AnswerResultsTupleScheme getScheme() {
      return new AnswerResultsTupleScheme();
    }
  }

  private static class AnswerResultsTupleScheme extends TupleScheme<AnswerResults> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AnswerResults struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetAnswerResults()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetAnswerResults()) {
        {
          oprot.writeI32(struct.answerResults.size());
          for (AnswerResult _iter12 : struct.answerResults)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AnswerResults struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.answerResults = new ArrayList<AnswerResult>(_list13.size);
          AnswerResult _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new AnswerResult();
            _elem14.read(iprot);
            struct.answerResults.add(_elem14);
          }
        }
        struct.setAnswerResultsIsSet(true);
      }
    }
  }

}

